#!/bin/bash

# set -x

script_path="$(readlink --canonicalize "$0")"
dir="$(dirname "$script_path")"

# shellcheck disable=1090
source "${dir}/.venv/bin/activate"

exec python "${script_path}.py" "$@"
